language: java
jdk:
    - oraclejdk8
sudo: false
install:
    - curl -o $HOME/.m2/settings.xml https://github.com/Naoghuman/lib-database-objectdb/blob/master/settings.xml
script: mvn clean install
cache:
    directories:
        - $HOME/.m2
